### ISSUE TITLE
Auto-open meet.google.com linked in the main channel

### ISSUE THREAD

**Issue by pgreze** [TheAxZim/Meet-Simultaneous-Interpretation#5]
Something like:

> As a JP speaker, I was shared the interpretation link in the main channel discussion chat, and clicked it to access the interpretation channel.

Not sure the UX is great, but Im posting it here if it can be helpful.

**Comment by TheAxZim** [comment]
Hmmm, I think this is too difficult to implement (reading from chat and detecting this and they may not want it to automatically open etc). Issue #4  solves it I think -- so I will close this ticket.
