### ISSUE TITLE
Channel name display

### ISSUE THREAD

**Issue by gbeckerman** [TheAxZim/Meet-Simultaneous-Interpretation#8]
How about writing the channel display to the following?
解釈チャンネル -> INTERPRETATION
メインのチャンネル -> MAIN

**Comment by TheAxZim** [comment]
@gbeckerman 
Do you mean, just remove the space from `解釈 チャンネル` and add `の` between `メイン チャンネル` ?
The translations are all here:
https://github.com/TheAxZim/Meet-Simultaneous-Interpretation/blob/main/src/_locales/ja/messages.json

**Comment by TheAxZim** [comment]
Closed the PR #11 and solved with different messages on PR #12 as discussed privately.
